model:
  n_layers: 3
  add_batchnorm: True
train:
  optimizer:
    name: Adam
    parameters:
      lr: 0.001
      betas: [0.9, 0.999]
  dataloader:
    batch_size: 32
    num_workers: 4
  n_epochs: 100